// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnosquareCodeExerciseAPI.Data;

namespace UnosquareCodeExerciseAPI.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211011101645_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UnosquareCodeExerciseAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AgeRestriccion")
                        .HasColumnType("int");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgeRestriccion = 12,
                            Company = "Mattel",
                            Description = "",
                            Name = "Barbie Developer",
                            Price = 25.99m
                        },
                        new
                        {
                            Id = 2,
                            AgeRestriccion = 4,
                            Company = "Marvel",
                            Description = "",
                            Name = "xyc",
                            Price = 75.5m
                        },
                        new
                        {
                            Id = 3,
                            AgeRestriccion = 18,
                            Company = "Nintendo",
                            Description = "",
                            Name = "abc",
                            Price = 99.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
